[workspace]
authors = ["Geoffrey Daniels <geoff@gpdaniels.com>"]
channels = ["conda-forge"]
name = "python-raw"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
service = { cmd = ["python", "service.py"], env = { PYTHONDONTWRITEBYTECODE = "1" } }

[dependencies]
python = ">=3.13.7,<3.14"
